import { Sparkles, Zap, AlertTriangle, Check, BookOpen, PlayCircle, HelpCircle, PlusCircle, UploadCloud, BrainCircuit, Download, ListChecks, Filter, Link2, Settings2, Database } from 'lucide-react';
import styles from './Workspace.module.css';

export default function WhyChooseModal({ isOpen, onClose }) {
  if (!isOpen) return null;

  return (
    <div className={styles.whyOverlay} onClick={onClose}>
      <div className={styles.whyModal} onClick={e => e.stopPropagation()}>
        <div className={styles.whyHeader}>
          <div className={styles.whyTitleWrapper}>
            <Sparkles size={22} style={{ color: '#a855f7' }} />
            <h3 className={styles.whyTitle}>Welcome to EggShell!</h3>
          </div>
          <button className={styles.whyCloseBtn} onClick={onClose} title="Close Welcome Screen">&times;</button>
        </div>
        
        <div className={styles.whyBody}>
          {/* Gorgeous Welcome Banner Card */}
          <div className={styles.welcomeBannerVertical}>
            <div className={styles.welcomeIntroSection}>
              <h4>Your Visual Data Pipeline Builder</h4>
              <p>
                We are thrilled to have you here! EggShell is the ultimate visual workspace for data stitching, multi-sheet relational joins, smart row filtering, custom conditional column mappings, and fully private browser automation.
              </p>
            </div>

            <div className={styles.welcomeToolsSection}>
              <h5>Workspace Tools Directory</h5>
              <div className={styles.welcomeToolsGrid}>
                <div className={styles.welcomeToolsItem}>
                  <PlusCircle size={16} style={{ color: '#f97316' }} />
                  <div>
                    <strong>Add Output File</strong>
                    <span>Create blank targeted output sheet layouts to wire mapped columns to.</span>
                  </div>
                </div>
                
                <div className={styles.welcomeToolsItem}>
                  <UploadCloud size={16} style={{ color: '#10b981' }} />
                  <div>
                    <strong>Import Layout</strong>
                    <span>Upload an existing spreadsheet template to automatically pre-fill targeted output columns.</span>
                  </div>
                </div>

                <div className={styles.welcomeToolsItem}>
                  <BrainCircuit size={16} style={{ color: '#a855f7' }} />
                  <div>
                    <strong>Scripting for AI support</strong>
                    <span>Generate visual pipeline mapping structures in one click with JSON configs that can be generated by AI.</span>
                  </div>
                </div>

                <div className={styles.welcomeToolsItem}>
                  <Download size={16} style={{ color: '#06b6d4' }} />
                  <div>
                    <strong>Export Pipeline</strong>
                    <span>Download the canvas configurations to automate future weekly/monthly reports in one click.</span>
                  </div>
                </div>

                <div className={styles.welcomeToolsItem}>
                  <Database size={16} style={{ color: '#3b82f6' }} />
                  <div>
                    <strong>Export Database & Collections</strong>
                    <span>Export your stitched pipelines as multi-sheet Excel workbooks, standalone SQLite databases, SQL dump scripts, or separate CSV files.</span>
                  </div>
                </div>
              </div>
            </div>
          </div>
          
          <div className={styles.whyShowcaseHeading}>
            <Sparkles size={16} style={{ color: '#f59e0b' }} /> Why EggShell Beats Excel
          </div>
          
          <div className={styles.comparisonGrid}>
            <div className={styles.comparisonCard}>
              <div className={styles.comparisonHeader}>
                <span className={styles.melderTag}>
                  <Zap size={10} style={{ fill: '#166534' }} /> EggShell Way
                </span>
                <h5 className={styles.comparisonTitle}>SQLite Database Engine</h5>
              </div>
              <p className={styles.comparisonText}>Powered by a real SQLite database. Operations are lightning-fast, fully relational, and can handle millions of rows in OPFS without a single crash.</p>
            </div>
            
            <div className={styles.comparisonCard}>
              <div className={styles.comparisonHeader}>
                <span className={styles.excelTag}>
                  <AlertTriangle size={10} style={{ fill: '#991b1b' }} /> Excel Way
                </span>
                <h5 className={styles.comparisonTitle}>Fragile & Heavy Sheets</h5>
              </div>
              <p className={styles.comparisonText}>Standard spreadsheets crash or lag with large rows. Formulas recalculate constantly, causing lag and silent data errors.</p>
            </div>

            <div className={styles.comparisonCard}>
              <div className={styles.comparisonHeader}>
                <span className={styles.melderTag}>
                  <Zap size={10} style={{ fill: '#166534' }} /> EggShell Way
                </span>
                <h5 className={styles.comparisonTitle}>Interactive Wiring Mappings</h5>
              </div>
              <p className={styles.comparisonText}>Wire files, joins, transformers, and conditions visually on an interactive canvas. You can trace your data logic step-by-step.</p>
            </div>

            <div className={styles.comparisonCard}>
              <div className={styles.comparisonHeader}>
                <span className={styles.excelTag}>
                  <AlertTriangle size={10} style={{ fill: '#991b1b' }} /> Excel Way
                </span>
                <h5 className={styles.comparisonTitle}>Messy & Hidden Formulas</h5>
              </div>
              <p className={styles.comparisonText}>Formulas are buried inside thousands of individual cells. Mismatched sorting requires tedious manual search and fixes.</p>
            </div>

            <div className={styles.comparisonCard}>
              <div className={styles.comparisonHeader}>
                <span className={styles.melderTag}>
                  <Zap size={10} style={{ fill: '#166534' }} /> EggShell Way
                </span>
                <h5 className={styles.comparisonTitle}>100% Client-Side Privacy</h5>
              </div>
              <p className={styles.comparisonText}>Processed completely in your local browser client. No file is ever uploaded to a server, guaranteeing absolute data privacy, 0 server lag, and zero subscription costs!</p>
            </div>
            
            <div className={styles.comparisonCard}>
              <div className={styles.comparisonHeader}>
                <span className={styles.excelTag}>
                  <AlertTriangle size={10} style={{ fill: '#991b1b' }} /> Excel Way
                </span>
                <h5 className={styles.comparisonTitle}>Server Syncing & Subscriptions</h5>
              </div>
              <p className={styles.comparisonText}>Requires heavy, recurring subscription payments, cloud connections, and uploading sensitive enterprise spreadsheets to external servers.</p>
            </div>

            <div className={styles.comparisonCard}>
              <div className={styles.comparisonHeader}>
                <span className={styles.melderTag}>
                  <Zap size={10} style={{ fill: '#166534' }} /> EggShell Way
                </span>
                <h5 className={styles.comparisonTitle}>On-The-Go Compilation</h5>
              </div>
              <p className={styles.comparisonText}>Filters, transforms, and conditional rules compile dynamically on the go. Any update recalculates instantly and shows up in the stitched table immediately.</p>
            </div>

            <div className={styles.comparisonCard}>
              <div className={styles.comparisonHeader}>
                <span className={styles.excelTag}>
                  <AlertTriangle size={10} style={{ fill: '#991b1b' }} /> Excel Way
                </span>
                <h5 className={styles.comparisonTitle}>Slow Manual Recalculation</h5>
              </div>
              <p className={styles.comparisonText}>Heavy sheets require pausing automatic updates to avoid crashing. Activating them requires hitting manually triggered update calculations.</p>
            </div>

            <div className={styles.comparisonCard}>
              <div className={styles.comparisonHeader}>
                <span className={styles.melderTag}>
                  <Zap size={10} style={{ fill: '#166534' }} /> EggShell Way
                </span>
                <h5 className={styles.comparisonTitle}>Cross-Sheet Global Logic</h5>
              </div>
              <p className={styles.comparisonText}>Run complex conditional logic and row filters across all joined datasets at once. Rules evaluate globally across all sheet boundaries effortlessly.</p>
            </div>

            <div className={styles.comparisonCard}>
              <div className={styles.comparisonHeader}>
                <span className={styles.excelTag}>
                  <AlertTriangle size={10} style={{ fill: '#991b1b' }} /> Excel Way
                </span>
                <h5 className={styles.comparisonTitle}>Brittle Cross-File Linking</h5>
              </div>
              <p className={styles.comparisonText}>Referencing columns in separate Excel files creates deep, rigid, and fragile link paths. Moving or renaming any file instantly breaks the entire sheet.</p>
            </div>

            <div className={styles.comparisonCard}>
              <div className={styles.comparisonHeader}>
                <span className={styles.melderTag}>
                  <Zap size={10} style={{ fill: '#166534' }} /> EggShell Way
                </span>
                <h5 className={styles.comparisonTitle}>AI-Assisted Auto Scripting</h5>
              </div>
              <p className={styles.comparisonText}>Export all sheet headers and pipeline schemas with one click. Paste them into ChatGPT, Claude, or Gemini to instantly generate perfect JSON automation configs and complex SQLite expressions!</p>
            </div>

            <div className={styles.comparisonCard}>
              <div className={styles.comparisonHeader}>
                <span className={styles.excelTag}>
                  <AlertTriangle size={10} style={{ fill: '#991b1b' }} /> Excel Way
                </span>
                <h5 className={styles.comparisonTitle}>Manual Formula Hunting</h5>
              </div>
              <p className={styles.comparisonText}>Search forums or web tutorials, trying to correctly nest complex combinations of VLOOKUP, IF, AND, and text functions to build basic logic.</p>
            </div>
          </div>
        </div>
        
        <div className={styles.whyFooter}>
          <button className={styles.whyActionBtn} onClick={onClose} style={{ display: 'inline-flex', alignItems: 'center', gap: '8px' }}>
            Got it, let's stitch! <Check size={16} />
          </button>
        </div>
      </div>
    </div>
  );
}
